### PR TITLE
Implement textDocument/formatting

### LINKED ISSUE #28: Implement textDocument/formatting
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_formatting

This will allow IDEs to format code, like `terraform fmt` would format it.

### PR DESCRIPTION
**Pull request by radeksimko**
Closes #28

### CODE REVIEW

**Comment by radeksimko** [comment]
I'm half thinking if it's worth still replacing the `hclwrite.Format` with a call out to `terraform fmt`. The only downside is a little more plumbing/mocking in tests and potentially different failure scenarios, but I'm still leaning more towards doing it.

**Comment by aeschright** [comment]
I think this looks good, aside from making a decision on that detail.

**Comment by musabmasood** [comment]
Dumb question, how can I enable this in vscode? `terraform fmt` doesn't seem to be running on save. Just updated to 2.0.1 plugin, everything else seems to be working fine.

**Comment by aeschright** [comment]
It uses the VSCode settings here: https://github.com/hashicorp/vscode-terraform/issues/375#issuecomment-642707592

You won't see a call out to `terraform fmt` specifically because it's routed through the language server.

**Pull request merged**
